[workspace]
members = ["primitive-from-enum", "primitive-enum-derive"]
resolver = "2"

[workspace.package]
authors = ["Rail Khusnutdinov <rail@33.run>"]
edition = "2021"

[patch.crates-io]
primitive-enum-derive = { path = "./primitive-enum-derive" }
